version: '3'

services:
  app:
    container_name: api_locadora_carros
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www/html
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=api_locadora_carros"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: api_locadora_carros
      MYSQL_ROOT_PASSWORD: root
    container_name: api_locadora_carros_db
    ports:
      - "3309:3306"
    volumes:
      - database:/var/lib/mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
